server:
  port: 8081

spring:
  datasource:
    #    generate-unique-name: false
    name: tacocloud
    url: jdbc:mysql://127.0.0.1:3306/tacocloud
    #    driver-class-name: org.h2.Driver
    username: root
    password: 123456



#  h2:
#    console:
#      enabled: true
#      settings:
#        trace: true
logging:
  level:
    root: info
    org.springframework.security: debug

#        web-allow-others: true


taco:
  page-size: 20
  strList:
    - 123
    - 234
    - 789